version: 'latest'
services:

  build-dev:
    image: hugomods/hugo:go-git
    container_name: dev-build
    command: server -D --poll 700ms
    volumes:
     - ".:/src"
    ports:
      - "1313:1313"
    profiles:
      - dev

  build-staging:
    image: hugomods/hugo:go-git
    container_name: build-staging
    command: hugo --environment staging --minify --enableGitInfo
    volumes:
     - ".:/src"
    profiles:
      - stage

  build:
    image: hugomods/hugo:go-git
    container_name: build
    command: hugo --minify --enableGitInfo
    volumes:
     - ".:/src"
    profiles:
      - prod

  web: 
    image: nginx:alpine
    container_name: web-server
    ports: 
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:Z
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:Z