baseURL: $HUGO_BASEURL
title: Siddharth C
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
enableGitInfo: true
googleAnalytics: $HUGO_GOOGLEANALYTICS

minify:
  disableXML: true

outputs:
    home:
      - HTML
      - RSS
      - JSON 

params:
  env: production 
  title: Siddharth C 
  description: "Portfolio"
  keywords: [Blog, Siddharth, Siddharth Chillale, Portfolio, PaperMod, Graphics, Programming, Lifestyle, C++]
  author: Siddharth Chillale
  
  DateFormat: "January 2, 2006"
  defaultTheme: light 
  disableThemeToggle: false
  
  
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  showToc: false
  

  assets:
    disableHLJS: true # to disable highlight.js
    favicon: "profile/sc_logo.png"
    favicon16x16: "profile/sc_logo.png"
    favicon32x32: "profile/sc_logo.png"
    

  label:
    text: Siddharth
    icon: profile/sc_logo.png
    iconHeight: 36

  profileMode:
    enabled: true 
    title_f: Siddharth
    title_l:  Chillale
    subtitle: "Software Developer | Data Engineering, Cloud Computing, Web Develpment"
    imageUrl: "/profile/SiddharthChillale_square.jpg"
    imageTitle: my image
    buttons:
      - name: Resume 📥 
        url: /docs/siddharth-chillale-resume.pdf
      - name: Projects 📑
        url: projects

  homeInfoParams:
    Title: "Schillale \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/SiddharthChillale"
    - name: linkedin
      url: "https://linkedin.com/in/schillal"
    - name: email
      url: "mailto:siddharth.chillale@gmail.com" 
    - name: twitter
      url: "https://twitter.com/TheLongRaven"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  editPost:
    URL: "https://github.com/siddharthchillale.github.io/content"
    Text: "Suggest Changes" 
    appendFilePath: true 

taxonomies:
  category: categories
  tag: tags
  series: series

frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date

imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 75
  resampleFilter: Box

menu:
  main:
    - identifier: Resume
      name: Resume 📥
      url: /docs/siddharth-chillale-resume.pdf
      weight: 1
    - identifier: Projects
      name: Projects 📑
      url: /projects/
      weight: 2
    - identifier: blog
      name: Blog 🧠
      url: /blog/
      weight: 3
    - identifier: About
      name: About 👤
      url: /about/
      weight: 4

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai