name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Print repo
        env: 
          HUGO_BASEURL: $ {{ vars.HUGO_BASEURL}}
        run: echo "HUGO_BASEURL = $HUGO_BASEURL"  
      
      - name: Print env
        env: 
          HUGO_BASEURLENV: $ {{ vars.HUGO_BASEURLENV}}
        run: echo "HUGO_BASEURLENV = $HUGO_BASEURLENV"

      - name: Build
        # env: 
        #   HUGO_BASEURL: ${{ vars.HUGO_BASEURL }}
        # run: hugo --minify -b https://siddharthchillale.github.io/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public